apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-redis-app
  labels:
    app: python-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-redis
  template:
    metadata:
      labels:
        app: python-redis
    spec:
      containers:
      - name: python-redis-app
        image: devopsvconn/redistest:latest
        ports:
        - containerPort: 80  # Assuming your Python application runs on port 8080
        env:
        - name: REDIS_HOST
          value: redis-headless.dmsng.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: python-redis-app
spec:
  selector:
    app: python-redis
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
